services:
  postgres:
    image: postgres:17
    container_name: shop_analyzer_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      shop_analyzer_network:
        aliases:
          - db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  
  redis:
    image: redis:7
    container_name: shop_analyzer_redis
    ports:
      - "6379:6379"
    networks:
      - shop_analyzer_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-shop-analyzer:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=shop_analyzer.settings
    networks:
      - shop_analyzer_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  shop_analyzer_network:
    driver: bridge
